import Foundation

extension AppStore {
    var usesChinese: Bool {
        selectedLanguage == "中文"
    }

    func t(_ key: String) -> String {
        guard usesChinese else { return key }
        return Self.zhCN[key] ?? key
    }

    func topicTitle(_ topic: DebateTopic) -> String {
        guard usesChinese else { return topic.title }
        return Self.zhCNTopics[topic.title] ?? topic.title
    }

    func topicDetails(_ topic: DebateTopic) -> String {
        guard usesChinese else { return topic.details }
        return Self.zhCNTopicDetails[topic.title] ?? topic.details
    }

    func category(_ value: String) -> String {
        t(value)
    }

    func debateMode(_ mode: DebateMode) -> String {
        t(mode.rawValue)
    }

    func debateFormat(_ format: DebateFormat) -> String {
        t(format.rawValue)
    }

    func debateDifficulty(_ difficulty: DebateDifficulty) -> String {
        t(difficulty.rawValue)
    }

    func debateSide(_ side: DebateSide) -> String {
        t(side.rawValue)
    }

    func speaker(_ role: SpeakerRole) -> String {
        t(role.rawValue)
    }

    func themeName(_ theme: AppTheme) -> String {
        t(theme.rawValue)
    }

    func memorySignalDetail(_ signal: MemorySignal) -> String {
        let prefix = "Most common completed debate category: "
        if signal.detail.hasPrefix(prefix) {
            let rawCategory = signal.detail
                .replacingOccurrences(of: prefix, with: "")
                .trimmingCharacters(in: CharacterSet(charactersIn: ". "))
            return "\(t("Most common completed debate category")): \(category(rawCategory))."
        }
        return t(signal.detail)
    }

    func debateCountText(_ count: Int) -> String {
        usesChinese ? "\(count) 场辩论" : "\(count) \(count == 1 ? "debate" : "debates")"
    }

    private static let zhCN: [String: String] = [
        "Home": "首页",
        "History": "历史",
        "Tools": "工具",
        "Settings": "设置",
        "OK": "确定",
        "Today's Practice": "今日练习",
        "Start Guided Practice": "开始引导练习",
        "Start Open Debate": "开始自由辩论",
        "Guided Practice": "引导练习",
        "Today's skill": "今日技能",
        "Worked example": "示范案例",
        "Use this checklist": "使用这份检查清单",
        "Practice motion": "练习辩题",
        "Learn the move": "学习技巧",
        "Debate for real": "实战辩论",
        "Get coached": "获得教练反馈",
        "Learn": "学习",
        "Review": "复盘",
        "Before you speak, check": "发言前检查",
        "You argue": "你方立场",
        "Rate yourself on today's skill": "先对今日技能自评",
        "The AI coach scores the same five skills": "AI 教练按同一套五项技能量表评分",
        "Retry one speech and compare": "重试一段发言并对比改进",
        "No practice motion available yet.": "暂时没有可用的练习辩题。",
        "Skill path": "技能路径",
        "Step": "步骤",
        "Next": "接下来",
        "Final step of the path": "路径的最后一步",
        "Path complete": "路径已完成",
        "Reviewing": "正在复习",
        "Practicing": "正在练习",
        "Current step": "当前步骤",
        "Mastered": "已掌握",
        "Master a skill with a 4+ coach score in two judged debates, or in one guided practice focused on it. Tap any step to practice it.": "在两场有裁判评分的辩论中该技能获得 4 分及以上，或在一次聚焦该技能的引导练习中获得 4 分及以上，即掌握该技能。点击任意步骤可直接练习。",
        "Strong scores": "高分评分",
        "Start": "开始",
        "min": "分钟",
        "What do you want to improve?": "你最想提升什么？",
        "Rhetorix will build a short practice plan around your goal. You can change these choices in Settings.": "Rhetorix 会围绕你的目标制定短时练习计划。之后可以在设置中修改。",
        "Primary goal": "主要目标",
        "Experience level": "经验水平",
        "Practice length": "练习时长",
        "Build My Practice Plan": "建立我的练习计划",
        "Your learning profile and debate history stay on this device.": "你的学习画像和辩论历史保存在本设备上。",
        "Learning Plan": "学习计划",
        "Debate competition": "竞赛辩论",
        "Classroom debates": "课堂辩论",
        "Speaking confidence": "表达自信",
        "English speaking": "英语口语",
        "Critical thinking": "批判性思维",
        "Beginner": "初学者",
        "Intermediate": "中级",
        "Advanced": "高级",
        "Argument structure": "论证结构",
        "Evidence and examples": "证据与案例",
        "Direct clash and rebuttal": "直接交锋与反驳",
        "Impact comparison": "影响比较",
        "Delivery and clarity": "表达与清晰度",
        "Build every argument as a claim, a warrant, and an impact.": "将每个论点构建为主张、论证桥梁和影响。",
        "Use a concrete example, explain its relevance, and avoid unsupported certainty.": "使用具体案例，解释其相关性，并避免无依据的确定性表达。",
        "Name the opponent's claim, challenge its weakest link, and explain why that changes the debate.": "明确对方主张，挑战其中最薄弱的环节，并说明这如何改变辩论。",
        "Compare probability, scale, timeframe, and reversibility instead of listing impacts.": "比较概率、规模、时间范围和可逆性，而不是只罗列影响。",
        "Signpost your ideas, finish each sentence, and make the decisive point easy to follow.": "清晰标示观点，完整表达每句话，让决定性论点易于理解。",
        "Claim → Why it is true → Why it matters": "主张 → 为什么成立 → 为什么重要",
        "Example → Source or basis → Link to the claim": "案例 → 来源或依据 → 与主张的联系",
        "They say → But → Because → Therefore": "对方说 → 但是 → 因为 → 所以",
        "Even if → Our impact matters more because": "即使如此 → 我方影响更重要，因为",
        "Signpost → One idea per sentence → Clear conclusion": "结构提示 → 每句一个观点 → 清晰结论",
        "Schools should teach AI literacy because students already use these systems without understanding their limits; this reduces misinformation and unsafe reliance.": "学校应教授 AI 素养，因为学生已经在不了解其局限的情况下使用这些系统；这能减少错误信息和不安全依赖。",
        "A school pilot is useful only if you explain who participated, what changed, and why that result applies to this motion.": "只有说明参与者、发生的变化以及结果为何适用于本辩题，学校试点案例才有价值。",
        "They say regulation stops innovation, but clear safety rules can increase adoption because schools and families trust accountable products.": "对方说监管会阻碍创新，但明确的安全规则能提高采用率，因为学校和家庭更信任可问责的产品。",
        "Even if compliance creates short-term cost, preventing widespread student harm is larger, harder to reverse, and affects more people.": "即使合规会产生短期成本，防止大范围学生伤害的规模更大、更难逆转且影响更多人。",
        "First, I will answer their cost argument. Second, I will show why our safety impact decides the debate.": "首先，我会回应对方的成本论点。其次，我会说明为什么我方的安全影响决定这场辩论。",
        "State one clear claim": "提出一个清晰主张",
        "Explain the causal link": "解释因果联系",
        "Finish with a concrete impact": "以具体影响结尾",
        "Use a specific example": "使用具体案例",
        "Explain why it is credible": "解释其可信性",
        "Connect it directly to the motion": "将其直接联系到辩题",
        "Quote or summarize their claim": "引用或概括对方主张",
        "Attack its warrant or evidence": "攻击其论证桥梁或证据",
        "Explain what the clash changes": "解释交锋改变了什么",
        "Compare both sides": "比较双方影响",
        "Use at least two weighing tests": "至少使用两项权衡标准",
        "State which impact decides the round": "说明哪个影响决定本场",
        "Signpost the speech": "标示发言结构",
        "Keep sentences focused": "让每句话聚焦",
        "End with a clear conclusion": "以清晰结论结束",
        "Challenge intelligence. Extend ideas.": "挑战智能，延展观点。",
        "Support Development": "支持开发",
        "All features are free. Donations help keep Rhetorix independent.": "所有功能免费。赞助帮助 Rhetorix 保持独立。",
        "Donate": "赞助",
        "Live Debate": "实时辩论",
        "Start Voice Debate": "开始语音辩论",
        "Start a timed debate": "开始限时辩论",
        "Quick Actions": "快捷操作",
        "New Debate": "新辩论",
        "Start a debate with AI": "与 AI 开始辩论",
        "Face-to-Face": "面对面辩论",
        "Debate on one device": "两人在同一设备辩论",
        "Review debates": "查看辩论记录",
        "Fallacy Detector": "谬误检测",
        "Analyze reasoning": "分析推理问题",
        "Preparation Tools": "准备工具",
        "Constructive Analysis": "立论分析",
        "Analyze opponent constructives": "分析对方立论",
        "Rebuttal": "反驳",
        "Fallacy": "谬误",
        "Debates": "辩论",
        "Win Rate": "胜率",
        "Win Streak": "连胜",
        "Memory": "记忆",
        "Real local memory": "真实本地记忆",
        "Learning": "学习中",
        "Build your debate profile": "建立你的辩论画像",
        "Choose your MBTI if you want Rhetorix to include it in your local profile. You can skip this.": "如果你愿意，可以选择 MBTI 加入本地画像；也可以跳过。",
        "Skip for now": "暂时跳过",
        "Rhetorix only infers traits from real local debate history. It will not invent a profile when evidence is insufficient.": "Rhetorix 只会从真实本地辩论历史推断画像；证据不足时不会编造结论。",
        "Memory Profile": "记忆画像",
        "MBTI": "MBTI",
        "Not set": "未设置",
        "Evidence": "证据样本",
        "debates": "场辩论",
        "Complete more debates to unlock reliable inferred profile signals.": "完成更多辩论后解锁更可靠的推断画像。",
        "Debate style": "辩论风格",
        "Value signal": "价值倾向",
        "Practice focus": "练习重点",
        "Style": "风格",
        "Values": "价值",
        "Focus": "重点",
        "Analytical / evidence-first": "理性/证据优先",
        "Values-first / persuasive": "价值/感染力优先",
        "Balanced reasoning style": "均衡推理风格",
        "Environment-focused": "环境议题倾向",
        "Animal welfare-focused": "动物保护倾向",
        "Topic interest": "话题兴趣",
        "Most common completed debate category": "最常见的已完成辩论类别",
        "Needs stronger evidence": "需要更强证据",
        "Needs more direct clash": "需要更直接交锋",
        "Needs clearer structure": "需要更清晰结构",
        "Needs stronger impact weighing": "需要更强影响权衡",
        "Needs clearer definitions": "需要更清晰定义",
        "Needs clearer delivery": "需要更清晰的表达",
        "Coach rubric scores for delivery and clarity are consistently low.": "教练量表中的表达与清晰度评分持续偏低。",
        "Evidence gaps in analyzed constructives": "已分析立论中的证据缺口",
        "Definition problems in analyzed constructives": "已分析立论中的定义问题",
        "Causal leaps in analyzed constructives": "已分析立论中的因果跳跃",
        "Impact weighing gaps in analyzed constructives": "已分析立论中的影响权衡缺口",
        "Slow rebuttal pacing": "反驳节奏偏慢",
        "Your recorded arguments more often use evidence, logic, policy costs, or causal framing.": "你的历史发言更常使用证据、逻辑、政策成本或因果框架。",
        "Your recorded arguments more often use fairness, rights, harm, or moral framing.": "你的历史发言更常使用公平、权利、伤害或道德框架。",
        "Your recorded arguments use analytical and values-based framing at similar levels.": "你的历史发言中理性框架和价值框架使用程度接近。",
        "Your history contains repeated environmental or climate-related debate evidence.": "你的历史中反复出现环境或气候相关辩论证据。",
        "Your history contains repeated animal welfare or animal rights debate evidence.": "你的历史中反复出现动物福利或动物权利相关辩论证据。",
        "Judging or rebuttal feedback mentions evidence, data, or support gaps.": "裁判或反驳反馈中提到证据、数据或支撑不足。",
        "Feedback mentions responding, rebutting, or directly engaging the other side.": "反馈中提到需要回应、反驳或正面处理对方观点。",
        "Feedback mentions structure, framework, organization, or clarity.": "反馈中提到结构、框架、组织或清晰度问题。",
        "Feedback mentions weighing, impact comparison, or why one side matters more.": "反馈中提到权衡、影响比较或重要性排序问题。",
        "Judge or training feedback mentions unclear definitions, scope, or framing.": "裁判或训练反馈中提到定义、范围或框定不清。",
        "Constructive Analysis repeatedly flags unsupported evidence or false-information risk in speeches you analyze.": "立论分析多次标记你分析过的发言存在证据不足或信息不实风险。",
        "Constructive Analysis repeatedly flags definition or scope problems in speeches you analyze.": "立论分析多次标记你分析过的发言存在定义或范围问题。",
        "Constructive Analysis repeatedly flags causal leaps or weak warrants in speeches you analyze.": "立论分析多次标记你分析过的发言存在因果跳跃或论证桥梁薄弱。",
        "Constructive Analysis repeatedly flags weak impact or weighing in speeches you analyze.": "立论分析多次标记你分析过的发言存在影响或权衡薄弱。",
        "Recorded stage timing shows rebuttal or reply turns often use most of the available time.": "记录的阶段用时显示，反驳或总结回合经常用掉大部分可用时间。",
        "Complete two debates to unlock real memory-based recommendations.": "完成两场辩论后解锁基于真实记忆的推荐。",
        "Details": "详情",
        "Open Memory Detail": "打开记忆详情",
        "Evidence-based": "基于证据",
        "Recommendation 2.0": "推荐 2.0",
        "Voice ratio": "语音比例",
        "Not enough data": "数据不足",
        "Recommended practice focus": "推荐练习重点",
        "Balances your interest in": "结合你的兴趣领域",
        "Targets": "针对",
        "Favorite area": "偏好领域",
        "Preferred mode": "偏好模式",
        "Completion rate": "完成率",
        "Average length": "平均长度",
        "Average stage time": "平均阶段用时",
        "Recommended topic": "推荐辩题",
        "Based on your completed debates in": "基于你在这个领域的真实辩论记录：",
        "Search topics...": "搜索辩题...",
        "Trending": "热门",
        "Select Topic": "选择话题",
        "Add Topic": "添加话题",
        "Custom debate topic": "自定义辩题",
        "Custom": "自定义",
        "Custom debate topic.": "自定义辩题。",
        "Custom Topic": "自定义辩题",
        "Topic title": "辩题标题",
        "Optional details": "补充说明（可选）",
        "Cancel": "取消",
        "Create Topic": "创建辩题",
        "Create a debate topic that is saved locally and can be reused.": "创建一个保存到本地、之后可重复使用的辩题。",
        "Use a custom topic": "使用自定义辩题",
        "Add Custom Topic": "添加自定义辩题",
        "Checking...": "检测中...",
        "Edit this topic in a future build.": "后续版本可编辑这个话题。",
        "Choose a Topic": "选择话题",
        "Proposition 1 Constructive": "正方一辩立论",
        "Opposition 1 Constructive": "反方一辩立论",
        "Proposition 2 Extension": "正方二辩扩展",
        "Opposition 2 Extension": "反方二辩扩展",
        "Proposition 3 Rebuttal": "正方三辩反驳",
        "Opposition 3 Rebuttal": "反方三辩反驳",
        "Opposition Reply": "反方总结陈词",
        "Proposition Reply": "正方总结陈词",
        "Define the motion, set the judging framework, and present the strongest opening case.": "定义辩题、建立评判框架，并提出最强开篇立论。",
        "Respond to definitions if needed, rebut the first case, and present the opposition case.": "必要时回应定义，反驳正方立论，并提出反方立论。",
        "Rebuild the proposition case, answer opposition attacks, and add a clear extension.": "重建正方论证，回应反方攻击，并加入清晰扩展。",
        "Rebuild the opposition case, answer proposition attacks, and add a clear extension.": "重建反方论证，回应正方攻击，并加入清晰扩展。",
        "Collapse to the decisive clashes, compare impacts, and avoid relying on brand-new arguments.": "聚焦决定性冲突，比较影响，不依赖全新论点。",
        "Summarize why opposition wins the debate. Do not introduce new arguments.": "总结反方为何赢下辩论。不要引入新论点。",
        "Summarize why proposition wins the debate and answer the opposition reply. Do not introduce new arguments.": "总结正方为何赢下辩论，并回应反方总结。不要引入新论点。",
        "Exchange arguments freely while still making claims, warrants, evidence, and impacts clear.": "自由交锋，但仍需清晰呈现主张、论证、证据和影响。",
        "Mode": "辩论模式",
        "Format": "辩论形式",
        "Difficulty": "难度",
        "Your Position": "你的立场",
        "AI Provider": "AI 提供方",
        "Start Debate": "开始辩论",
        "Debate Setup": "辩论设置",
        "Thinking...": "思考中...",
        "Type your argument...": "输入你的论点...",
        "Speak or type your argument...": "说出或输入你的论点...",
        "Listening...": "正在聆听...",
        "Voice is primary. Text remains available.": "优先使用语音，也可以输入文字。",
        "Tap the keyboard button to type instead of speaking.": "点击键盘按钮可切换为文字输入。",
        "Voice": "语音",
        "Auto-read AI responses": "自动朗读 AI 回答",
        "Uses the iPhone system voice. If speech is unavailable, debate text still works normally.": "使用 iPhone 系统语音。即使朗读不可用，辩论文本也会正常显示。",
        "Voice Engine": "语音引擎",
        "System Voice": "系统语音",
        "Volcengine": "火山引擎",
        "Voicebox": "Voicebox",
        "Volcengine App ID": "火山引擎 App ID",
        "Volcengine Access Token": "火山引擎 Access Token",
        "Volcengine Cluster": "火山引擎 Cluster",
        "Volcengine Voice Type": "火山引擎 Voice Type",
        "Voice Speed": "语速",
        "Voicebox Server URL": "Voicebox 服务地址",
        "Voicebox Profile ID": "Voicebox 语音档案 ID",
        "Voicebox Engine": "Voicebox 引擎",
        "Voicebox Model Size": "Voicebox 模型大小",
        "Use a LAN or remote Voicebox server URL on a real iPhone. 127.0.0.1 only works when the server runs on the same device or simulator host.": "真机请使用局域网或远程 Voicebox 服务地址。127.0.0.1 只适合同设备或模拟器宿主机。",
        "Online voice engines read AI responses when configured. System voice remains the fallback if online speech is unavailable.": "配置在线语音引擎后会优先朗读 AI 回答；在线语音不可用时自动回退到系统语音。",
        "Volcengine reads AI responses when configured. System voice remains the fallback if online speech is unavailable.": "配置火山引擎后会优先朗读 AI 回答；在线语音不可用时自动回退到系统语音。",
        "Read AI response": "朗读 AI 回答",
        "Stop AI voice": "停止 AI 朗读",
        "Stage Timer": "阶段计时",
        "Text": "文字",
        "AI": "AI",
        "AI Turn": "AI 发言",
        "End": "结束",
        "Ending...": "正在结束...",
        "Reflect before seeing the judge": "查看裁判反馈前先反思",
        "Rate the speech you actually gave. The coach scores stay hidden until you finish this reflection.": "请评价你实际完成的发言。完成反思前，教练评分将保持隐藏。",
        "One thing I would change next time": "下次我会改变的一件事",
        "Optional reflection": "反思（可选）",
        "See Coach Feedback": "查看教练反馈",
        "Self-Assessment": "自我评估",
        "Your view and the coach's view": "你的评价与教练评价",
        "Coach": "教练",
        "Five-skill coach rubric": "五项技能教练量表",
        "Improve one speech now": "现在改进一段发言",
        "Choose a speech, apply the feedback, and compare the retry with your first attempt.": "选择一段发言，应用反馈，并将重试与第一次尝试进行比较。",
        "Retry this speech": "重试这段发言",
        "Retry again": "再次重试",
        "Original speech": "原始发言",
        "Apply this correction": "应用这项改进",
        "Your revised speech": "你的修改版发言",
        "Compare My Retry": "比较我的重试",
        "Retry comparison": "重试对比",
        "Retry Speech": "重试发言",
        "The retry was saved. Review the two versions and try to make the next improvement more explicit.": "重试已保存。比较两个版本，并让下一次改进更加明确。",
        "Debate": "辩论",
        "Support": "支持",
        "Oppose": "反对",
        "Turn": "回合",
        "Winner": "胜者",
        "N/A": "暂无",
        "No judgment yet.": "尚未评分。",
        "Transcript": "记录",
        "Round Memory": "本场记忆",
        "No timing memory recorded for this debate yet.": "这场辩论还没有记录阶段用时。",
        "No timing": "未计时",
        "Timed": "已计时",
        "Debate Result": "辩论结果",
        "Why the judge decided": "裁判判决理由",
        "Key clashes": "关键交锋",
        "Strongest support arguments": "支持方最强论点",
        "Strongest oppose arguments": "反对方最强论点",
        "Improvement actions": "改进建议",
        "Next practice focus": "下一次训练重点",
        "Help Rhetorix recommend better topics": "帮助 Rhetorix 推荐更合适的辩题",
        "Category feedback changes future topic recommendations. Technique feedback is recorded but does not change recommendations.": "类别反馈会影响未来辩题推荐；技巧反馈只会记录，不影响推荐。",
        "What do you like about it?": "你喜欢它的哪一点？",
        "What do you dislike about it?": "你不喜欢它的哪一点？",
        "Like": "喜欢",
        "Dislike": "不喜欢",
        "Category": "类别",
        "Technique": "技巧",
        "Saved": "已保存",
        "Liked category": "喜欢的类别",
        "Disliked category": "不喜欢的类别",
        "Based on your feedback for": "基于你对这个类别的反馈：",
        "turns": "回合",
        "Rebuttal Training": "反驳训练",
        "Score": "得分",
        "Map claims and rebuttals": "分析立论与可反驳点",
        "Rebuttal Trainer": "反驳训练",
        "Timed rebuttal practice": "限时反驳练习",
        "Logic Fallacy Detector": "逻辑谬误检测",
        "Find weak reasoning": "发现薄弱推理",
        "Tools support your debates. Live debate remains the main workflow.": "工具用于辅助辩论，实时辩论仍是主流程。",
        "AI Hallucination Detector": "AI 幻觉检测",
        "Open GPTZero hallucination detector": "打开 GPTZero 幻觉检测工具",
        "Appearance": "外观",
        "Theme": "主题",
        "Language": "语言",
        "English": "English",
        "中文": "中文",
        "Dark": "深色",
        "Pink White": "粉白浅色",
        "AI Providers": "AI 提供方",
        "Enabled": "已启用",
        "Disabled": "已禁用",
        "Enable": "启用",
        "API Key": "API Key",
        "API Configuration": "API 配置",
        "Model": "模型",
        "Custom Model": "自定义模型",
        "Base URL": "Base URL",
        "Save Configuration": "保存配置",
        "Test Connection": "测试连接",
        "Test whether this provider and model can respond before saving.": "保存前测试这个提供方和模型能否正常响应。",
        "Connection successful.": "连接成功。",
        "Connection failed.": "连接失败。",
        "Configuration saved.": "配置已保存。",
        "Map Mode": "图谱模式",
        "Key": "关键",
        "Preparing node text...": "正在生成节点文本...",
        "AI Prep Text": "AI 备赛文本",
        "Refresh AI Text": "刷新 AI 文本",
        "Provider": "提供方",
        "Generate with AI": "用 AI 生成",
        "Generating...": "生成中...",
        "Prep": "准备",
        "Clash": "冲突",
        "Drill": "训练",
        "Use this node to build your constructive speech.": "用这个节点构建你的立论发言。",
        "Use this node to compare which side wins the debate.": "用这个节点比较哪一方更能赢下辩论。",
        "Practice answering this attack out loud before the round.": "赛前用这个节点练习回应攻击。",
        "Analyze for Fallacies": "分析逻辑谬误",
        "Analyzing fallacies...": "正在分析逻辑谬误...",
        "Paste constructive speech": "粘贴立论文本",
        "Analyze": "分析",
        "Live recording analysis": "录音实时分析",
        "Start Recording": "开始录音",
        "Stop Recording": "停止录音",
        "Turn on recording to transcribe and analyze each detected claim.": "开启录音后，App 会转写并逐条分析检测到的论点。",
        "Live recording requires a physical iPhone. Paste text to test in Simulator.": "录音实时分析需要真机。在模拟器中请使用粘贴文本测试。",
        "Analyzing new claim...": "正在分析新论点...",
        "No constructive analysis yet.": "还没有立论分析结果。",
        "Detected claims": "检测到的论点",
        "Tap to view rebuttal points": "点击查看可反驳点",
        "Original quote": "原文摘录",
        "Why this can be challenged": "为什么可被反驳",
        "Rebuttable points": "可反驳点",
        "Logical fallacy": "逻辑谬误",
        "Unsupported evidence": "证据不足",
        "False information risk": "信息不实风险",
        "Missing warrant": "论证桥梁缺失",
        "Causal leap": "因果跳跃",
        "Overgeneralization": "过度概括",
        "Definition problem": "定义问题",
        "Contradiction": "自相矛盾",
        "Personal attack": "人身攻击",
        "Impact weakness": "影响论证薄弱",
        "Other": "其他",
        "High": "高",
        "Low": "低",
        "未检出": "未检出",
        "No logical fallacies were detected in this text.": "这段文本中没有检测到明显逻辑谬误。",
        "Topic": "话题",
        "Generate Argument": "生成待反驳观点",
        "Choose a topic before generating a practice argument.": "生成练习观点前请选择辩题。",
        "Generate an opponent argument to start the 2.5-minute rebuttal timer.": "生成对方观点后会启动 2.5 分钟反驳计时器。",
        "Argument to resist": "待反驳观点",
        "Submit Rebuttal": "提交反驳",
        "Scoring...": "评分中...",
        "Thank you for supporting Rhetorix": "感谢支持 Rhetorix",
        "Scan with WeChat or Alipay": "使用微信或支付宝扫码",
        "All features are free. Donations help maintain the app and add new features.": "所有功能免费。赞助会帮助维护应用并添加新功能。",
        "User vs AI": "人机辩论",
        "AI vs AI": "AI 对 AI",
        "Face to Face": "面对面",
        "Structured": "结构化",
        "Free Flow": "自由交流",
        "Easy": "简单",
        "Medium": "中等",
        "Hard": "困难",
        "You": "你",
        "Judge": "裁判",
        "Technology": "科技",
        "Society": "社会",
        "Ethics": "伦理",
        "Economics": "经济",
        "Politics": "政治",
        "Environment": "环境",
        "Work": "工作",
        "Education": "教育",
        "Health": "健康",
        "Urban Policy": "城市政策",
        "Science": "科学",
        "Law": "法律",
        "Media": "媒体",
        "Philosophy": "哲学"
    ]

    private static let zhCNTopics: [String: String] = [
        "Should AI be regulated by governments?": "政府是否应该监管人工智能？",
        "Is universal basic income a good idea?": "全民基本收入是好主意吗？",
        "Is social media doing more harm than good?": "社交媒体是否弊大于利？",
        "Will AI replace most human jobs?": "AI 会取代大多数人类工作吗？",
        "Should euthanasia be legal?": "安乐死是否应该合法化？",
        "Is cryptocurrency the future of money?": "加密货币是货币的未来吗？"
    ]

    private static let zhCNTopicDetails: [String: String] = [
        "Should AI be regulated by governments?": "讨论政府是否应监管人工智能的发展与使用。",
        "Is universal basic income a good idea?": "比较经济安全、工作激励和公共成本。",
        "Is social media doing more harm than good?": "评估心理健康、公共讨论、错误信息和人际连接。",
        "Will AI replace most human jobs?": "辩论自动化、新工作创造和经济转型。",
        "Should euthanasia be legal?": "讨论自主权、保护机制、痛苦和医疗责任。",
        "Is cryptocurrency the future of money?": "比较去中心化、波动性、监管和采用程度。"
    ]
}
